import Image from "next/image"; import Link from "next/link"; import { ArrowRight, ArrowUpRight } from "@/components/icons";
import { ProductCard } from "@/components/product-card"; import { Newsletter } from "@/components/newsletter"; import { products } from "@/data/catalog";
export default function Home(){return <main id="main"><section className="hero"><div className="hero-copy"><div className="hero-index"><span className="eyebrow">SOVA / Skin, in its own rhythm</span><span>01 — 05</span></div><div className="hero-copy-main"><p className="small-rule">A considered way to care</p><h1>Care that feels like <em>second nature.</em></h1><p>Thoughtful essentials for the skin you live in. Comfortable textures, familiar ingredients, and room to make the ritual your own.</p><div className="hero-actions"><Link className="button button-dark" href="/shop">Explore the collection <ArrowUpRight size={17}/></Link><Link className="text-link" href="/routine">Find your routine <ArrowRight size={17}/></Link></div></div><div className="hero-bottom"><span>Simple by design.</span><span>Made for real life.</span></div></div><div className="hero-visual"><Image src="/images/hero.png" alt="SOVA skincare collection with botanical details on warm limestone" fill priority sizes="(max-width: 800px) 100vw, 58vw"/><span className="hero-visual-caption">THE DAILY COLLECTION / SOVA</span></div></section>
<section className="intro-strip"><span>01 / THE COLLECTION</span><p>Quietly effective routines begin with products you <em>want</em> to use.</p><Link href="/shop" className="circle-link" aria-label="Explore all products"><ArrowUpRight size={23}/></Link></section>
<section className="section-pad"><div className="section-heading"><div><span className="eyebrow">Best sellers · Concept assortment</span><h2>Good care, <em>made simple.</em></h2></div><Link className="text-link" href="/shop">Shop all products <ArrowUpRight size={17}/></Link></div><div className="product-grid home-products">{products.filter(p=>p.featured).map(product=><ProductCard key={product.id} product={product}/>)}</div></section>
<section className="editorial-panel"><div className="editorial-image"><Image src="/images/texture.png" alt="Close-up of clear serum and soft cream on warm stone" fill sizes="(max-width: 800px) 100vw, 50vw"/></div><div className="editorial-copy"><span className="eyebrow">02 / A softer point of view</span><h2>Less noise.<br/><em>More feeling.</em></h2><p>Skincare can be a clear, comforting part of the day. SOVA is built around tactile textures, understandable ingredients, and a routine that fits your pace.</p><Link className="underlined-link" href="/philosophy">Our philosophy <ArrowUpRight size={17}/></Link></div></section>
<section className="ingredient-feature section-pad"><div><span className="eyebrow">03 / Inside the formula</span><h2>Familiar ingredients.<br/><em>Thoughtful purpose.</em></h2></div><div><p>From water-loving glycerin to softening squalane, every ingredient has a role. Explore plain-language explanations, then see which concept products include them.</p><Link href="/ingredients" className="button button-outline">Explore ingredients <ArrowUpRight size={17}/></Link></div><div className="ingredient-names" aria-hidden="true"><span>Glycerin</span><span>Squalane</span><span>Oat</span></div></section>
<section className="routine-feature"><div className="routine-feature-copy"><span className="eyebrow">04 / Your skin, your rhythm</span><h2>A routine with <em>room for you.</em></h2><p>Answer three simple, cosmetic questions. We’ll suggest an easy order of use based on how your skin feels and how much time you want to spend.</p><Link className="button button-dark" href="/routine">Build your routine <ArrowUpRight size={17}/></Link><small>Concept guidance only · no diagnosis</small></div><div className="routine-feature-art"><div className="routine-orbit"><span>01<br/>CLEANSE</span><span>02<br/>CARE</span><span>03<br/>MOISTURIZE</span></div><Image src="/images/moisture-treatment.png" alt="SOVA moisturizer and treatment against a warm clay setting" fill sizes="(max-width: 800px) 100vw, 50vw"/></div></section>
<section className="section-pad feature-last"><div className="section-heading"><div><span className="eyebrow">05 / Beyond the face</span><h2>A little care, <em>everywhere.</em></h2></div><Link href="/products/body-quiet-lotion" className="text-link">Meet Body Quiet <ArrowUpRight size={17}/></Link></div><div className="body-feature"><Image src="/images/body.png" alt="SOVA body lotion beside linen and a lotion swipe" fill sizes="(max-width: 800px) 100vw, 55vw"/><div><span className="eyebrow">Body care / 250 ml</span><h3>Body Quiet Lotion</h3><p>For the slower minute after a shower. A daily lotion concept with a soft, comfortable finish.</p><Link className="underlined-link" href="/products/body-quiet-lotion">Explore body care <ArrowUpRight size={17}/></Link></div></div></section>
<section className="journal-preview section-pad"><span className="eyebrow">Notes from SOVA</span><h2>Curiosity looks <em>good on you.</em></h2><div><Link href="/ingredients"><span>01 / Ingredients</span><strong>What does a humectant actually do?</strong><ArrowUpRight/></Link><Link href="/philosophy"><span>02 / Philosophy</span><strong>The beauty of a shorter routine</strong><ArrowUpRight/></Link><Link href="/routine"><span>03 / Routine</span><strong>Find an order that feels easy</strong><ArrowUpRight/></Link></div></section><Newsletter/></main>}
