"use client";
import { useEffect, useMemo, useState } from "react";
import { categories, products, Category } from "@/data/catalog"; import { ProductCard } from "@/components/product-card";
type Sort = "featured" | "price-low" | "price-high" | "name";
const isCategory=(value:string):value is Category=>categories.includes(value as Category);
const isSort=(value:string):value is Sort=>["featured","price-low","price-high","name"].includes(value);
export function ShopClient({initialCategory,initialSort}:{initialCategory:string;initialSort:string}){
  const [category,setCategory]=useState<Category|"All">(isCategory(initialCategory)?initialCategory:"All"); const [sort,setSort]=useState<Sort>(isSort(initialSort)?initialSort:"featured");
  useEffect(()=>{const sync=()=>{const params=new URLSearchParams(window.location.search);const cat=params.get("category")??"";const order=params.get("sort")??"";setCategory(isCategory(cat)?cat:"All");setSort(isSort(order)?order:"featured");};window.addEventListener("popstate",sync);return()=>window.removeEventListener("popstate",sync);},[]);
  function apply(nextCategory:Category|"All",nextSort:Sort){setCategory(nextCategory);setSort(nextSort);const params=new URLSearchParams();if(nextCategory!=="All")params.set("category",nextCategory);if(nextSort!=="featured")params.set("sort",nextSort);const query=params.toString();window.history.pushState(null,"",query?`/shop?${query}`:"/shop");}
  const shown=useMemo(()=>{const list=products.filter(product=>category==="All"||product.category===category);if(sort==="price-low")list.sort((a,b)=>a.priceCents-b.priceCents);if(sort==="price-high")list.sort((a,b)=>b.priceCents-a.priceCents);if(sort==="name")list.sort((a,b)=>a.name.localeCompare(b.name));return list;},[category,sort]);
  return <><div className="shop-controls"><div className="filter-row" role="group" aria-label="Filter by category">{(["All",...categories] as const).map(item=><button type="button" key={item} className={category===item?"filter active":"filter"} aria-pressed={category===item} onClick={()=>apply(item,sort)}>{item}</button>)}</div><label className="sort-label">Sort by <select value={sort} onChange={event=>apply(category,event.target.value as Sort)}><option value="featured">Featured</option><option value="price-low">Price: low to high</option><option value="price-high">Price: high to low</option><option value="name">Name: A to Z</option></select></label></div><div className="shop-count" role="status">Showing {shown.length} {shown.length===1?"product":"products"}{category!=="All"?` in ${category}`:""}</div>{shown.length?<div className="product-grid shop-grid">{shown.map(product=><ProductCard key={product.id} product={product}/>)}</div>:<div className="empty-state"><h2>No products in this view.</h2><button className="button button-dark" type="button" onClick={()=>apply("All","featured")}>Clear filters</button></div>}{(category!=="All"||sort!=="featured")&&<button className="reset-filter" type="button" onClick={()=>apply("All","featured")}>Clear filters and sort</button>}</>;
}
